name: Deploy FCAI SUMMARIES to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/FCAI_Summaries

            git pull origin main

            sudo systemctl reload nginx